### ISSUE TITLE
C++ volatile support

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/tool-conventions#60] opened 2018-08-06 23:43 UTC
Recently we had a few discussions on how to support C++ `volatile`. Some discussion thread started in [this CL](https://reviews.llvm.org/D49194) (the CL itself was not terribly relevant though; the discussions went in the comments below) and [the CG meeting on July 24](https://github.com/WebAssembly/meetings/blob/master/2018/CG-07-24.md). While the discussion in the CG meeting was very informative, the topic is not directly relevant with the wasm spec itself, so maybe this repo is a better place for future discussions.

Summary of discussions so far:
- LLVM's `-fms-volatile` option turns volatiles into atomics, and this option is the default for MSVC, so there is a precedent for turning volatiles into atomic operations by default in LLVM.
- asm.js fastcomp also currently converts volatiles to atomics.
- @jfbastien suggested we should be user friendly by converting volatiles into atomics. For larger sizes not supported naturally by wasm, we can even tear them, because volatiles can tear. If we turn volatile load/stores into regular load stores, the volatile's guarantee that every byte should be touched only once per instruction is not satisfied anymore.
- Some people expressed concerns that by converting volatiles into sequentially consistent atomics, we are making it too strong, and if we support relaxed memory models in future, code that used to work might break.
- @sunfishcode suggested we'd better be consistent with other targets, and people who what to use that feature should turn on the option.

**Comment by aheejin** [comment] 2018-08-06 23:48
@dschuff @conrad-watt

**Comment by jfbastien** [comment] 2018-08-06 23:50
I'm not suggesting `-fms-volatile`, just pointing out the precedent! In particular, I think the transformation from `volatile` in LLVM IR to seq_cst which tear when not lock-free should occur when lowering to WebAssembly (i.e. the LLVM optimizer sees `volatile`).

**Comment by aheejin** [comment] 2018-08-07 00:00
@jfbastien 
> I'm not suggesting -fms-volatile, just pointing out the precedent! 
Sorry for the inaccuracies. Fixed them.

> In particular, I think the transformation from volatile in LLVM IR to seq_cst which tear when not lock-free should occur when lowering to WebAssembly (i.e. the LLVM optimizer sees volatile).
Do you mean by non-atomic volatiles by 'not lock-free'?
Also, is the reason you think we should do it late is to distinguish volatiles from atomics, I think?

**Comment by jfbastien** [comment] 2018-08-07 04:51
I mean:

* `store volatile i32` should become a single atomic store because it's guaranteed to be lock-free on WebAssembly.
* `store volatile i128` (or anything which isn't guaranteed lock-free on WebAssembly) should become as many atomic stores as are required so that each sub atomic store is lock-free.

**Comment by aheejin** [comment] 2018-08-07 23:31
@jfbastien Thanks for the clarification!
@sunfishcode Do you have any concerns or suggestions so far?

**Comment by sunfishcode** [comment] 2018-08-08 03:45
-fms-volatile does turn out to be a little more subtle than just "translate volatile to atomic", so it may not be the best solution here. On the other hand, it already exists, and might be close enough for practical purposes, so it's worth considering.

My main concern is, if we've decided that users using volatile aren't intending to ask for strict volatile semantics, giving them strict volatile semantics as long as we can through the optimizer seems unhelpful. It seems better to add atomic in the frontend, if that's what we think is needed.

This is in part because compiler writers are being encouraged to optimize atomics. We can't just look at what one optimizer does today; we need to consider that more optimizations might be added in target-independent code in the future, and possibly what other optimizers might do. The most straightforward approach seems to be to describe whatever we decide the desired semantics are, from the frontend.

**Comment by Daniel-Abrecht** [comment] 2018-08-08 04:11
Atomic and volatile are two completly unrelated concepts. Volatile is for things like memory mapped IO pins on uCs and such stuff, it only means that all reads and writes to it must really be performed, but nothing else. Atomic only means that reading and writing to a variable always result in a consistent state, and nothing else. One doesn't imply the other, they can't replace the other one. Treating volatile as atomic makes no sense to me. And optimizing volatile would be completly crazy, it's a devs way of telling the compiler it can't know what will happen if it uses it, so the compiler can't make any assumptions for volatile variables, and thus can't optimize them. And if some devs use the wrong one in their code, then the code is just wrong and should be fixed, but even then there is already an option to work arround that.

**Comment by jfbastien** [comment] 2018-08-08 05:07
@Daniel-Abrecht I think you're missing much of the context for this discussion.

**Comment by jfbastien** [comment] 2018-08-08 05:17
@sunfishcode 

> My main concern is, if we've decided that users using volatile aren't intending to ask for strict volatile semantics, giving them strict volatile semantics as long as we can through the optimizer seems unhelpful. It seems better to add atomic in the frontend, if that's what we think is needed.

This is in the context of pre-existing code migrating to WebAssembly. In that context the code already has volatile semantics from the compiler, and what we're trying to do is to preserve some of the ordering guarantees such that the VM's optimizer doesn't mess things up. With that double context, I don't see why adding atomic in the frontend is better. Can you explain?

> This is in part because compiler writers are being encouraged to optimize atomics.

Guilty :-)

It's worth noting that these optimizations are valid for atomic, but often not for volatile (exception in limited circumstances). Transforming volatile to pure atomic, say in the clang frontend, would lose some semantics which I believe are important.

It's also important to notice that the optimizations allowed on WebAssembly's own atomics are vastly different from those allowed in C++.

**Comment by aheejin** [comment] 2018-08-08 23:04
@Daniel-Abrecht We are aware of that, but mostly in old code some people have used volatiles for similar purposes, so we are discussing what to do considering user-friendliness. Comments in [this CL](https://reviews.llvm.org/D49194) has details how this discussion started.

**Comment by sunfishcode** [comment] 2018-08-09 15:01
One of the differences between volatile and atomic in the spec is that volatile does not, by itself, communicate between threads. To make the kind of code under discussion here work, we'd need to interpret volatile in source code as a construct that does.

Let's say we decide to do that. LLVM IR hasn't been a party to this decision though, so if we leave it as plain `volatile` in LLVM IR, the optimizer will interpret it that to mean it doesn't communicate between threads. An optimization that reasons about the places where communication between threads could occur could break our code (without even "optimizing volatile" per se, but rather by reasoning about where atomics etc. do and don't occur).

Consider the reason why the -fms-volatile flag itself was added to clang. If a traditional treatment of volatile was sufficient to let legacy code survive the optimizer, why was this flag needed? It's that the optimizer *is* reasoning about atomics and volatiles *today*, in ways that actually matter, including to the very kind of legacy code that this whole conversation is about.

**Comment by jfbastien** [comment] 2018-08-09 16:05
I'm making a very different point: we're considering x86 code which mistakenly uses volatile for a variety of reasons. That code Happens To Work™, in LLVM, today. LLVM, in these circumstances, applies its usual `volatile` optimizations and the x86 goes TSO on it. Now the developer wants to transition to WebAssembly. The LLVM optimizations were and still are semantics preserving (in the sense that the *broken* program semantics are nonetheless preserved). The problem is in LLVM IR → WebAssembly translation: we have 3 choices.

1. Refuse all `volatile` inputs.
2. Transform to non-atomic.
3. Transform to `seq_cst` atomic.

Here's how I value each option and why:

1. Is user hostile. I'm working on deprecating much of `volatile` in C++ itself, and WebAssembly is absolutely the wrong place to start preaching. Compilers should be doing that job, and only when users are ready for it (i.e. upgrade to C++20 and get a deprecation warning, upgrade to C++23 and get compile error, all the while tooling helps you upgrade).
2. Is *invalid* because the WebAssembly optimizer lost information, and code is now optimizable in a manner which doesn't preserve the (broken!) program semantics anymore. WebAssembly doesn't need to come in and be a pedant about it because it has a clear and simple way to be nice. Again, this isn't the time and place to snark at users. Remember that atomic didn't exist in C++ before C++11, pthread wasn't perfect and definitely wasn't available everywhere.
3. Is the only choice we have.

> Consider the reason why the -fms-volatile flag itself was added to clang. If a traditional treatment of volatile was sufficient to let legacy code survive the optimizer, why was this flag needed? It's that the optimizer is reasoning about atomics and volatiles today, in ways that actually matter, including to the very kind of legacy code that this whole conversation is about.

No, it was added to clang to match the precise behavior of MSVC, because *broken* code which targeted Windows assumed that behavior, and clang decided to be nice to those *mistaken* users and grant them the same behavior. If these users want to target WebAssembly they should use `-fms-volatile`, but that's a separate discussion from what we should do as the default for all other developers.

**Comment by sunfishcode** [comment] 2018-08-09 22:14
I applaud C++ standards-level work to fix volatile, and agree that it's not something we should try to do through wasm.

> The problem is in LLVM IR → WebAssembly translation

As far as I'm aware, the actual problem here is that there is C++ code which people wish to port to wasm, and it sometimes doesn't work. We aren't constrained to solve it in any particular place in the toolchain, as long as we solve the actual problem.

> 2. Is *invalid* because the WebAssembly optimizer lost information, and code is now optimizable in a manner which doesn't preserve the (broken!) program semantics anymore.

The only standard that applies is the C++ standard, where volatile doesn't imply communication. What's *valid* is for the optimizer or wasm engine to break the kinds of programs we're discussing. But we're looking at our options outside the scope of the standard (without breaking programs that do follow the rules), so I don't rule out 2. here.

> No, it was added to clang to match the precise behavior of MSVC, because broken code which targeted Windows assumed that behavior, and clang decided to be nice to those mistaken users and grant them the same behavior.

Take another look:

  - code developed on some existing platform
  - uses volatile to communicate between threads, works as intended on existing platform
  - mostly works on new platform, but has some problems related to volatile
  - compiler writers decide to modify the compiler to help

Other than subtle details, this is the same situation. Eerily similar. It's so similar, that -fms-volatile is practically the solution already, with the only apparent questions being whether it's worth adding a whole new option to do the same thing with minor differences, and whether it should be on by default.

[I grant](https://github.com/WebAssembly/tool-conventions/issues/60#issuecomment-411274986) that -fms-volatile may not be precisely what we might want, but I also observe that the general approach of addressing this issue in the front-end is more robust, easier to explain to users, easier to implement consistently in case other compilers want to do the same thing, more manageable in the case of LTO between libraries where some are legacy code and some are not, *and* it's the place where other clang developers have already fixed practically the same problem in a different context.

**Comment by aheejin** [comment] 2018-08-10 16:17
@jfbastien What was the _broken_  semantics that MSVC programmers used and how it is different from the kind of legacy program are we trying to support?

**Comment by dschuff** [comment] 2018-08-11 00:46
@aheejin I think there is disagreement on what those semantics are; i.e. I think we are in agreement that it makes sense to offer the "broken" semantics that most code is written for, but there are 2 different ideas on what the situation with the existing code is.

One idea is that the code "already has volatile semantics from the compiler" and is therefore correct under those semantics, but was written for a different architecture; and therefore we need only prevent the wasm VM (which may have more powerful optimizations than existing hardware) from doing things that the C++ compiler and hardware wouldn't have. 
This assumes that the code is prepared for those semantics and the possible middle-end optimizations they allow. That assumption is at least partially valid since the compiler does optimize volatiles some already (stipulating that it does work today on some compiler and architecture).

The other idea is that the code really isn't correct under volatile semantics; that "users using volatile aren't intending to ask for strict volatile semantics" and that today's working code only works accidentally, on compilers which don't do as many optimizations as they'd be allowed to. Therefore we need to prevent the wasm VM *and the C++ compiler* (i.e. the middle end) from doing optimizations that they don't do for volatiles today.


Under idea 1, I think that keeping volatiles in the middle end and then lowering to atomics in the backend makes sense, in that this situation is closest to what the code would see today when targeting existing architectures. It also happens to be what emscripten/asmjs already does (making the tiny amount of already-ported code continue to work the same, for whatever that's worth).

Under idea 2, the code is not prepared for strict volatile semantics. It may be broken when ported from e.g. MSVC to wasm, or from older gcc/clang to wasm, or from older clang to more powerful current/future clang even on its original platform. For this code especially, something like -fms-volatile would be more likely to protect it from the middle-end optimizations.

I agree that it's easier to specify what the guarantees are if we do something in the frontend. I think that if we believe idea 1, then we could even potentially relax the volatile->atomic lowering in the future if we get new primitives, and only actually *guarantee* that we have strict semantics (these semantics would be in terms of LLVM volatile though, not C++ volatile; it doesn't seem too likely that someone not using LLVM would implement LLVM's volatile semantics, they'd just implement C++ or some other language).

Also we've been talking about optimizations that may affect volatiles but not atomics; until now I hadn't thought about the opposite, i.e. optimizations on atomics but not volatiles. For example turning 2 atomic increments into a single one. Presumably that's why -fms-volatile marks the operations as both atomic and volatile. Because of that we can't really get away with only reasoning about atomics. Whatever we end up with with will have to explicitly deal with LLVM volatiles and atomics, both together and in isolation. Also even if we have a solution in the frontend, other frontends could hand us volatiles anyway. Because of that we'll have to deal directly with any LTO issues that may arise, regardless of what we do in the frontend. In general we can't just say that this is only clang's problem, or that a frontend-only solution is enough.

Since we have to do *something* with LLVM atomics when they hit the backend, I think it makes the most sense to lower them to atomics in the straightforward way. I also think that we should look closer at -fms-volatile and make it "just work" with wasm's clang/LLVM. We can advocate that as the way to (mostly) protect your volatile-using code from all of the optimizers without having to think too much. The only remaining question is what should be the default. 
I'm not super opinionated about that but I'm inclined in general to be less magical; in other words, fewer deviations from existing platforms unless the user opts in (and to be clear, I do consider automatic ms-volatile to be fairly magical).
I guess I'm also more inclined to trust that the user has tested their volatile-using code enough to know that it works on x86 or ARM on some compiler, and that they'll have to test it again when they build it with *any* other compiler for any architecture (i.e. more in the camp of "idea 1" above). If we make this assumption, then we can more easily pass along benefits that come from the mid-level optimizations.

**Comment by aheejin** [comment] 2018-08-13 22:48
@dschuff I can easily imagine what kind of program falls into the idea 2; I guess they are the ones using volatiles to communicate between threads, and also they are the ones with the _broken_ semantics @jfbastien was referring to, right? But I don't know what would fall into the idea 1, and not sure which semantics you meant by "they already have volatile semantics from the compiler". Do you mean they use correct volatile semantics according to C++ spec but still have chances to fail in the current wasm VM? Could you give some examples? In this thread we are talking about two kinds of broken semantics and that's basically what I'm not sure about.

**Comment by dschuff** [comment] 2018-08-14 16:25
Both "idea 1" and "idea 2" are ideas of what the "broken" semantics mean. Another way to describe the difference is to say that the semantics of idea 1 are closer to "real" volatile semantics. The quote, "they already have volatile semantics from the compiler" was from @jfbastien above. I think he meant that the programs, despite the fact that they really want something usable with threads, are in fact using volatiles today; so the compiler is already applying optimizations based on volatile semantics, and the programs are working with those optimizations enabled. Therefore, continuing to apply the middle-end optimizations for volatiles (while doing the minimum in the backend to keep things correct according to the relevant specs) is the closest thing to the way that these programs are already being compiled.

**Comment by dschuff** [comment] 2018-08-15 17:52
I think my previous wall of text was too long. So I'll summarize my opinion:
1. We should lower "volatile" from LLVM IR to atomics in the straightforward way, which will preserve true LLVM/C volatile semantics. I expect this should be uncontroversial.
2. We should offer (and perhaps even encourage) ms-volatile as an option (I expect this should also be uncontroversial), however:
3. I favor keeping volatile in the IR by default. I'm not convinced that our likely volatile user cares about the distinctions between volatile and atomic semantics (and if they do, we can't really help them specifically anyway). However this situation is the closest to the conditions that the code was originally written for; it represents the smallest amount of change we can apply compared to how the code was likely tested before.

**Comment by sunfishcode** [comment] 2018-08-15 22:40
> 1. We should lower "volatile" from LLVM IR to atomics in the straightforward way, which will preserve true LLVM/C volatile semantics. I expect this should be uncontroversial.

A straightforward way to preserve true LLVM/C/C++ volatile when translating into wasm is to ignore volatile (setjmp and signals are handled specially, and the platform has no memory-mapped I/O).

Now, say we want to support C++ code which wants volatile to communicate between threads (even though no spec supports it). LLVM's optimizer sometimes breaks code that does this. And even if something works today, it might not work if the code ever changes, the compiler is ever upgraded, the build flags change, libraries change, or other things. So anything we might do in codegen would be an incomplete solution at best. However, we *can* support such code reliably by using atomic in the frontend. And, if we do that, doing something in codegen too would be redundant, and may even give people the wrong impression.

And yes, all frontends producing LLVM IR will need to use atomic if they need atomic. I think it's well within LLVM norms to expect frontend writers in 2018 to follow rules like "don't use volatile for threads".

> 3. I favor keeping volatile in the IR by default. I'm not convinced that our likely volatile user cares about the distinctions between volatile and atomic semantics (and if they do, we can't really help them specifically anyway). However this situation is the closest to the conditions that the code was originally written for; it represents the smallest amount of change we can apply compared to how the code was likely tested before.

It would be helpful if someone could name some actual code that this conversation is about. If we set aside C++ code developed on Windows, on the assumption that -fms-volatile is the right answer for such code by definition, and set aside code that isn't useful to port to wasm, what kind of code is out there?

In my experience, perspectives like @Daniel-Abrecht's above are mainstream. Even MSVC, which invented /volatile:ms (which -fms-volatile emulates), [strongly recommends using /volatile:iso](https://msdn.microsoft.com/en-us/library/12a04hfd.aspx#Anchor_1). This is also the default behavior of clang.

I care about this issue in part because I'm thinking about maintainability. If the C++ committee ever removes or revamps volatile, or LLVM ever changes the way it handles volatile, or someone wants to port another C/C++ compiler to wasm, I don't want wasm's volatile to be a special thing that we have to think about.

**Comment by dschuff** [comment] 2018-08-23 18:15
> A straightforward way to preserve true LLVM/C/C++ volatile when translating into wasm is to ignore volatile (setjmp and signals are handled specially, and the platform has no memory-mapped I/O).

I don't think this is true. My understanding is that wasm VMs are allowed to do things like hoist loads (of constant addresses) out of loops, or do dead store elimination for ordinary loads and stores; both of those would break LLVM volatile semantics.

More specifically, let's say you searched for Dekker's algorithm in C. [here](http://jakob.engbloms.se/wp-content/uploads/2008/01/dekker.c) is one of the top hits:
```
static volatile int flag1 = 0;
static volatile int flag2 = 0;
static volatile int turn  = 1;
static volatile int gSharedCounter = 0;
int gLoopCount;
int gOnePercent;

void dekker1( ) {
        flag1 = 1;
        turn  = 2;
        while((flag2 ==  1) && (turn == 2)) ;
        // Critical section
        gSharedCounter++;
        // Let the other task run
        flag1 = 0;
}
```

If the loads of `flag2` and `turn` are not atomic, can't the VM hoist them out of the loop, making it potentially infinite? The C compiler is not allowed to do that for volatiles, so you could even say that this code is "correct" if it was written for a platform consisting of C on top of x86 or SPARC with TSO.

**Comment by sunfishcode** [comment] 2018-08-23 19:59
[LLVM's LangRef section on volatile](http://llvm.org/docs/LangRef.html#volatile-memory-accesses) says there's "no cross-thread synchronization behavior". LLVM's documentation is not particularly clear in this area, but it's meant to carry C/C++ volatile semantics, and even Wikipedia finds the space to document that C/C++'s volatile is [the wrong choice for this kind of thing](https://en.wikipedia.org/wiki/Dekker%27s_algorithm#Notes).

To be sure, I'm not opposed to supporting C code like this. What I'm saying is, the robust way is to translate volatile as atomic, in the frontend. And in fact, clang already has code to do this, in -fms-volatile. So the main question is how best to present this for users.

**Comment by dschuff** [comment] 2018-08-23 21:11
Even though it doesn't make the same guarantees about ordering, the standard does say that volatile operations should not be optimized out, that implementations cannot change the number of operations on a volatile object. Hoisting them out of a loop clearly violates that rule.

The unusual thing here is that currently the only way to observe that violation in existing embeddings is with another thread.

**Comment by sunfishcode** [comment] 2018-08-23 22:49
The C and C++ standards don't define volatile in terms of optimizations, and you can get away with a lot under the as-if clause. LLVM does, though it only discusses IR-level optimization and backends, and doesn't say anything about the ISA. And in fact, some physical platforms do reorder accesses which were originally marked volatile. What wasm engines are doing here isn't fundamentally different from a cache hierarchy that doesn't propagate stores between cores without explicit synchronization.

To be sure, I'm not opposed to supporting C code like this. What I'm saying is, the robust way is to translate volatile as atomic, in the frontend. And in fact, clang already has code to do this, in -fms-volatile. So the main question is how best to present this for users.

**Comment by jfbastien** [comment] 2018-08-23 23:56
> The C and C++ standards don't define volatile in terms of optimizations

That's incorrect.

K&R:

> The purpose of volatile is to force an implementation to suppress optimization that could otherwise occur. For example, for a machine with memory-mapped input/output, a pointer to a device register might be declared as a pointer to volatile, in order to prevent the compiler from removing apparently redundant references through the pointer.

D&E C++:

> To match ANSI C, the volatile modifier was introduced to help optimizer implementers.

C++17 Standard, [dcl.type.cv]:

> The semantics of an access through a volatile glvalue are implementation-defined. If an attempt is made to access an object defined with a volatile-qualified type through the use of a non-volatile glvalue, the behavior is undefined.
>
> [ Note: volatile is a hint to the implementation to avoid aggressive optimization involving the object because the value of the object might be changed by means undetectable by an implementation. Furthermore, for some implementations, volatile might indicate that special hardware instructions are required to access the object. See [intro.execution] for detailed semantics. In general, the semantics of volatile are intended to be the same in C++ as they are in C. —end note]

C17 Standard:

> A volatile declaration may be used to describe an object corresponding to a memory-mapped input/output port or an object accessed by an asynchronously interrupting function. Actions on objects so declared shall not be "optimized out" by an implementation or reordered except as permitted by the rules for evaluating expressions.

You cannot get away with much under the as-if rule when it comes to `volatile`. I've explained why transforming volatile to atomic in the frontend isn't sufficient. At a minimum you should do volatile atomic. I've also explained why that's a bad idea.

I honestly don't understand what you're trying to drive to. The approach I propose is eminently simple and I believe entirely correct, which also being nice to developers. I'd like to understand why you don't like it. It seems from the discussion above that we're not talking about the same volatile?

**Comment by jfbastien** [comment] 2018-08-24 16:56
I don't think you're understand standards well enough if your interpretation of non-normative notes and design rationale is "they're non-normative," however confusing this may be. Standards aren't perfect gems which are entirely correct, and the committee is well aware of how poorly worded volatile is.

> * This ensures that whatever semantics we decide that we need are consistently preserved through the entire optimization pipeline, even in the event of a compiler upgrade with new optimizations. Or the user tweaks their code and it inlines differently and different optimizations apply. Or a library changes. And so on.

Transforming volatile to atomic in the frontend does not do what you describe here. Further, doing this in the frontend needlessly creates a weird platform divergence.

> * Being friendly only in the backend comes with the risk that code could come to depend on it, which could put an awkward burden on us, the maintainers, when we want to release new versions, if anything has changed in the front-end or middle-end which breaks the code.

The same applies to changes in the frontend with one difference: if what I propose breaks then it does so for all platforms, whereas with your proposal it only does so for WebAssembly.

> *Non-C/C++ front-end writers producing LLVM IR can be reasonably expected to follow standards better than legacy C/C++ code, particularly when it comes to rules as simple and well-known in today's era as "don't use volatile for threads".

I don't think we're talking about languages other than C and C++. I suggest starting a separate thread for those.

> * -fms-volatile is already a thing in clang, and (to the level of detail we're discussing at this point), it's already exactly what we need here. The code is already there, it already works on wasm, we just need to decide what the UI should be

As I've explained, it's not exactly what we need. Users can opt-in to it, but it doesn't have the right semantics.

> * -fms-volatile is also an indication that other people, faced with the same problem, also decided that the right place to solve the problem is in the front-end.

Your understanding of how this flag came to be is historically inaccurate. This flag exists to match MSVC's x86 behavior. MSVC's x86 behavior exists because people who implemented MSVC had a mistaken understanding of what volatile meant (from a time when that mistaken understanding was common), they now regard it as a mistake they're stuck with. Thankfully for them that "mistake" isn't very costly on x86. It is on ARM, which is why MSVC has *different* behavior for volatile when targeting ARM.

> * If we want to handle corner cases like bitfields, enums, various struct cases, and so on, and explain the rules to end users, we'll need the frontend, because we won't always know what these are in LLVM IR.

This isn't WebAssembly's fight. I'm going to fix the languages (C and C++) and teach the frontend to do the right thing for all platforms.

> * Semantics consisting of "volatile through the optimizer, and atomic after that" are pretty tricky to reason about, and could be awkward to implement precisely in another C compiler wishing to be compatible with wasm.

Other C compilers can make their own choices, and if they go down the same route then they'll offer the same volatile semantics as with their own non-WebAssembly target. Developers aren't porting code from LLVM-wasm to GCC-wasm, they're porting code from LLVM-x86 or LLVM-arm to LLVM-wasm.



Let's get back to what I asked earlier:

> I honestly don't understand what you're trying to drive to. The approach I propose is eminently simple and I believe entirely correct, which also being nice to developers. I'd like to understand why you don't like it. It seems from the discussion above that we're not talking about the same volatile?

I still don't understand what you think is flawed with the approach I propose. I've systematically explained why what you propose is flawed, often I've made the exact same point and they don't seem to get through. I don't think we're talking about the same thing, and we're going in circles. This is very unproductive.

**Comment by sunfishcode** [comment] 2018-08-24 17:05
If you've stated, anywhere in this thread, why -fms-volatile isn't the semantics we want here, I can't find it.

**Comment by jfbastien** [comment] 2018-08-24 17:08
> If you've stated, anywhere in this thread, why -fms-volatile isn't the semantics we want here, I can't find it.

https://github.com/WebAssembly/tool-conventions/issues/60#issuecomment-411288138

**Comment by sunfishcode** [comment] 2018-08-24 17:10
-fms-volatile transforms volatile to volatile atomic.

**Comment by sunfishcode** [comment] 2019-06-16 17:47
Here's an update on the current status:

I used confusing language in some of my earlier posts. When I talked about "translating volatile to atomic", I should have said "translationg volatile to volatile atomic". This preserves the volatileness as long as possible, and it is what -fms-volatile does.

JF's standards proposal about `volatile` is [now published](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1152r0.html). It doesn't appear to deprecate or clarify any aspects of `volatile` discussed in this issue.

I have spoken with other C++ committee members who agreed that my interpretation of `volatile` and the footnotes quoted above are within the intent of the standard.

I still find the following solution best:
 - By default, have the wasm backend ignore volatile qualifiers, as it does now.
 - If needed, enable the -fms-volatile flag for use on wasm targets.

**Comment by jfbastien** [comment] 2019-06-17 16:54
> I have spoken with other C++ committee members who agreed that my interpretation of `volatile` and the footnotes quoted above are within the intent of the standard.

* Who have you spoken to? Very few people in the committee actually understand `volatile`. If you're going to appeal to authority, I'd like to know which authority and how authoritative it is.
* What is your interpretation of `volatile` that they agree with? Forgive me, but this thread is long and needs summarizing.
* Which are the "footnotes quoted above" which "are within the intent of the standard"? Your earlier argument was that footnotes didn't matter because they're non-normative.

I don't think you're looking for feedback here, is that correct?

**Comment by sunfishcode** [comment] 2019-06-18 13:12
> Who have you spoken to? Very few people in the committee actually understand volatile. If you're going to appeal to authority, I'd like to know which authority and how authoritative it is.

Ok, I appeal to Richard Smith, [editor of the C++ standard](https://github.com/cplusplus/draft/blob/master/source/cover-wd.tex#L12), who I caught up with several months ago and asked about this topic.

> What is your interpretation of volatile that they agree with? Forgive me, but this thread is long and needs summarizing.

It's conforming to lower C++ volatile accesses into regular non-atomic accesses at the wasm level.

> Which are the "footnotes quoted above" which "are within the intent of the standard"? Your earlier argument was that footnotes didn't matter because they're non-normative.

I mean [these footnotes](https://github.com/WebAssembly/tool-conventions/issues/60#issuecomment-415609017). And yes, these notes provide guidance to avoid "optimization", not requirements. This reflects how many C++ implementations work, but isn't how volatile is defined.

> I don't think you're looking for feedback here, is that correct?

Some of the difficulty in the earlier discussion may have been due to my mistake of describing -fms-volatile as "translate volatile to atomic" instead of "translate volatile to volatile atomic". I'm correcting that  now, so perhaps we can proceed to discuss -fms-volatile as part of the overall strategy here.

I propose that -fms-volatile is the best way to support legacy C++ code which uses volatile to communicate between threads (short of changing the code). In particular, it's better than translating volatile to atomic in the wasm backend, because (a) there's precedent for it -- -fms-volatile already exists (b) it's easier to explain to users what -fms-volatile does, in terms of their own code rather than compiler internals, and (c) if atomic is actually what's needed, we should use it throughout the optimizer, not just in the backend. A downside is that this solution doesn't automatically help non-C/C++ frontends, however I think it's acceptable to just ask such frontends to fix the problem on their end.

If we agree on that, we can then discuss whether to enable -fms-volatile by default on wasm. I propose we don't, because that would make us different from other targets, because code might come to implicitly depend on it, and because it might exacerbate confusion among users about what volatile really implies. I even see this as being aligned with the spirit of "Deprecating Volatile" -- we can't get rid of volatile entirely, but we can reduce its scope to just the things that really need it.

**Comment by jfbastien** [comment] 2019-06-18 16:19
OK I think I now understand your update, thanks!

Something we haven't talked about (I think?) is adding a diagnostic in clang, only when compiling for a wasm target, to the effect that `volatile` doesn't have the semantics developers expect on a wasm VM. IIUC a big part of your worry is exactly this: `volatile` really doesn't have semantics, but people mistakenly use it (either because they wrote the code before C++11 atomic, or because they don't know better e.g. coming from Java).

The trick here would be to only apply the diagnostic when generating `volatile` memory accesses: there are "valid" C++ type system uses for `volatile` when going silly generic programming (to change overload preference).

With a diagnostic (call it `-Wvolatile` for now) it seems like it's pretty much impossible to inadvertently rely on behavior, and we can suggest using `-Wno-volatile` *or* `-fms-volatile` as a solution to the diagnostic. Enabling either would squelch the warning.

I think that meets what you outline? And it also nudges code bases towards a more correct / current usage of the language.

**Comment by sunfishcode** [comment] 2019-06-24 22:51
Yeah, a `-Wvolatile` (or whatever we end up calling it) as you describe it here makes sense to me.

**Comment by sunfishcode** [comment] 2022-03-19 10:52
To summarize:
 - The wasm backend should, and already does, ignore volatile qualifiers.
 - -fms-volatile should not be, and already is not, enabled by default.
 - A reasonable patch to make -fms-volatile usable with the wasm backend would be accepted.
 - A reasonable patch implementing a -Wvolatile flag would be accepted.

**Closed by sunfishcode** 2022-03-19 10:52 UTC
