### ISSUE TITLE
relocation issues

### ISSUE THREAD

**Issue by carlokok** [WebAssembly/tool-conventions#22] opened 2017-10-02 16:16 UTC
Having used the relocations llvm emits I see a few missing things:

* the memory indexes work with global indexes; problem here is that a lot of symbols won't have a global (for example in debug info); I temporarily solved this by using a negative global index (-1) with Addend containing the original address.

* debug info needs some kind of "index into function"; In my local llvm I hacked in a new relocation type R_WEBASSEMBLY_FUNCTION_OFFSET_I32 which is the offset inside the function block for this.

**Comment by sbc100** [comment] 2017-10-16 21:34
Regarding the debug symbols, since we essentially model the symbol table using wasm globals it sounds like the maybe the problem is that all the debug symbols should be included as wasm globals but are not.   My understanding is that all relocations should reference a symbol and that all symbols should be wasm globals.  Would this work for your use case?

I'm not sure I understand the "index into function" relocation.  Wouldn't that be a constant?   I mean the function number would need a relocation but the offset within a given function should be the same after linking/relocation shouldn't it?

**Comment by carlokok** [comment] 2017-10-17 05:08
Re globals; Either option would work yes. I went for an additional "index into data" relocation because they didn't have a name at all so giving them random names would seem a bit unclean. But it would work yes.

Index into function: I used llvm here as a model with dwarf (which pretty much just works), but dwarf requires a pointer sized item that refers to a code offset. That's why I went he way of using a new relocation.  The alternative would be to use a function index + relative offset. Which of course is possible but would require a different debug info format.

**Comment by sbc100** [comment] 2017-10-20 21:46
I ran across this issue with the unnamed debug relocations recently.  Looks like the way ELF does it is to make symbols for the start of each section and then use "symbol + offset" as usual.  So you end up with symbols called ".text",  ".data", etc.  I think we can/should do the same for wasm

**Comment by sbc100** [comment] 2018-04-18 22:36
I believe this should be addressed in https://reviews.llvm.org/D44184

**Closed by sbc100** 2018-04-18 22:36 UTC
Labels: Linking
